apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::288441763335:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-JXERBEHA269K
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::288441763335:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-03T22:58:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "805"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 250ad5cd-7be8-48f7-8ce8-08b423bfc94f
